name: Pull Request CI

on:
  pull_request:
    branches:
      - "main"
    #   - "branch-target-test"
    types:
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run echo command
        run: echo "hello"
